# Generated by Django 5.1.7 on 2025-03-22 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting'), ('csrf', 'Cross-Site Request Forgery'), ('data_exposure', 'Sensitive Data Exposure'), ('auth_failure', 'Authentication Failure'), ('misconfiguration', 'Security Misconfiguration'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('location', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('date_discovered', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scanresult')),
                ('web_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.webapplication')),
            ],
        ),
        migrations.AddField(
            model_name='scanresult',
            name='web_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.webapplication'),
        ),
    ]
